### PR TITLE
Fix flaky testcase

### LINKED ISSUE #90: TAP testcase 'simple expires test' sometimes failed (flaky?)
https://github.com/tarantool/expirationd/runs/3910102548?check_suite_focus=true

```
TAP version 13
1..10
    # simple expires test
    1..4
    ok - checking start time
    ok - checking task name
    ok - checking restart count
    not ok - Test task executed and moved to archive
make: *** [Makefile:39: test] Error 1
      ---
      filename: ./test.lua
      trace:
      - line: 296
        source: '@./test.lua'
        filename: ./test.lua
        what: Lua
        namewhat: local
        name: fun
        src: ./test.lua
      - line: 218
        source: '@builtin/tap.lua'
        filename: builtin/tap.lua
        what: Lua
        namewhat: method
        name: test
        src: builtin/tap.lua
      - line: 0
        source: '@./test.lua'
        filename: ./test.lua
        what: main
        namewhat: 
        src: ./test.lua
      line: 0
      expected: 7
      got: 8
      ...
    # simple expires test: end
not ok - failed subtests
  ---
  filename: ./test.lua
  trace:
  - line: 245
    source: '@builtin/tap.lua'
    filename: builtin/tap.lua
    what: Lua
    namewhat: method
    name: test
    src: builtin/tap.lua
  - line: 0
    source: '@./test.lua'
    filename: ./test.lua
    what: main
    namewhat: 
    src: ./test.lua
  planned: 4
  failed: 1
  line: 0
  ...
    # execution error test
    1..2
    ok - checking restart count
    ok - Error task executed
    # execution error test: end
```

Tarantool version 2.8

How-To reproduce:

```
$ INDEX_TYPE='HASH' ./test.lua
```

### PR DESCRIPTION
**Pull request by ligurio**
suite: simple expires test
testcase: Test task executed and moved to archive

Fixes #90

### CODE REVIEW

File: test.lua [hunk 1]
```diff
@@ -343,7 +343,14 @@ test:test('simple expires test',  function(test)
     test:is(task.name, "test", 'checking task name')
     local restarts = 1
     test:is(task.restarts, restarts, 'checking restart count')
```
Comment (olegrok) [inline test.lua:345]: Shouldn't restart be checked in the same way?

**Review by olegrok — APPROVED** [review]

File: test.lua (hunk 1 above)
Comment (ligurio) [reply test.lua:345]: I believe no. `task.restarts` is a simple counter that changes synchronously, while the `expired_tuples_count` is a counter too, but it depends on the asynchronous operation.

**Comment by ligurio** [comment]
5 test workflow restarts without failed testcases,
https://github.com/tarantool/expirationd/actions/runs/1449203699
