### PR TITLE
test: fix flaky 'simple expires test'

### LINKED ISSUE #90: TAP testcase 'simple expires test' sometimes failed (flaky?)
https://github.com/tarantool/expirationd/runs/3910102548?check_suite_focus=true

```
TAP version 13
1..10
    # simple expires test
    1..4
    ok - checking start time
    ok - checking task name
    ok - checking restart count
    not ok - Test task executed and moved to archive
make: *** [Makefile:39: test] Error 1
      ---
      filename: ./test.lua
      trace:
      - line: 296
        source: '@./test.lua'
        filename: ./test.lua
        what: Lua
        namewhat: local
        name: fun
        src: ./test.lua
      - line: 218
        source: '@builtin/tap.lua'
        filename: builtin/tap.lua
        what: Lua
        namewhat: method
        name: test
        src: builtin/tap.lua
      - line: 0
        source: '@./test.lua'
        filename: ./test.lua
        what: main
        namewhat: 
        src: ./test.lua
      line: 0
      expected: 7
      got: 8
      ...
    # simple expires test: end
not ok - failed subtests
  ---
  filename: ./test.lua
  trace:
  - line: 245
    source: '@builtin/tap.lua'
    filename: builtin/tap.lua
    what: Lua
    namewhat: method
    name: test
    src: builtin/tap.lua
  - line: 0
    source: '@./test.lua'
    filename: ./test.lua
    what: main
    namewhat: 
    src: ./test.lua
  planned: 4
  failed: 1
  line: 0
  ...
    # execution error test
    1..2
    ok - checking restart count
    ok - Error task executed
    # execution error test: end
```

Tarantool version 2.8

How-To reproduce:

```
$ INDEX_TYPE='HASH' ./test.lua
```

### PR DESCRIPTION
**Pull request by oleg-jukovec**
The test used timings with a resolution of 1 second to remove tuples by expiration time. Sometimes the timings overlapped and an 'extra' tuple was removed. An 'extra' from the test point of view.

It is possible to extend the timings resolution and fix the problem.

The patch acts in a different way. It changes the input data so as not to depend on timings. In addition, the test is now faster.

Closes #90 

A flaky example from CI:
```
INDEX_TYPE='TREE' SPACE_TYPE='vinyl' ./test.lua
TAP version 13
1..10
    # simple expires test
    1..4
    ok - checking start time
    ok - checking task name
    ok - checking restart count
    not ok - Test task executed and moved to archive
      ---
      filename: ./test.lua
      trace:
      - line: 296
        source: '@./test.lua'
        filename: ./test.lua
        what: Lua
        namewhat: local
        name: fun
        src: ./test.lua
      - line: 218
        source: '@builtin/tap.lua'
        filename: builtin/tap.lua
        what: Lua
        namewhat: method
        name: test
        src: builtin/tap.lua
      - line: 0
        source: '@./test.lua'
make: *** [Makefile:38: test] Error 1
        filename: ./test.lua
        what: main
        namewhat: 
        src: ./test.lua
      line: 0
      expected: true
      got: false
      ...
    # simple expires test: end
tarantool.log:
2022-07-12 10:11:35.992 [2142] main/103/test.lua I> Running tests for TREE index and engine memtx
2022-07-12 10:11:35.996 [2142] main/103/test.lua I> -------------- put ------------
2022-07-12 10:11:35.996 [2142] main/103/test.lua I> put to space "origin"
2022-07-12 10:11:35.997 [2142] main/103/test.lua I> ------------- print -----------
2022-07-12 10:11:35.997 [2142] main/103/test.lua I> before print space "origin"
2022-07-12 10:11:35.997 [2142] main/103/test.lua I> [0, 'test_0@tarantool.org', 1657620695]
2022-07-12 10:11:35.997 [2142] main/103/test.lua I> [1, 'test_1@tarantool.org', 1657620696]
2022-07-12 10:11:35.997 [2142] main/103/test.lua I> [2, 'test_2@tarantool.org', 1657620697]
2022-07-12 10:11:35.997 [2142] main/103/test.lua I> [3, 'test_3@tarantool.org', 1657620698]
2022-07-12 10:11:35.997 [2142] main/103/test.lua I> [4, 'test_4@tarantool.org', 1657620699]
2022-07-12 10:11:35.997 [2142] main/103/test.lua I> [5, 'test_5@tarantool.org', 1657620700]
2022-07-12 10:11:35.997 [2142] main/103/test.lua I> [6, 'test_6@tarantool.org', 1657620701]
2022-07-12 10:11:35.997 [2142] main/103/test.lua I> [7, 'test_7@tarantool.org', 1657620702]
2022-07-12 10:11:35.997 [2142] main/103/test.lua I> [8, 'test_8@tarantool.org', 1657620703]
2022-07-12 10:11:35.997 [2142] main/103/test.lua I> [9, 'test_9@tarantool.org', 1657620704]
2022-07-12 10:11:35.997 [2142] main/103/test.lua I> [10, 'test_10@tarantool.org', 1657620705]
2022-07-12 10:11:35.997 [2142] main/103/test.lua I> [11, 'test_11@tarantool.org', '']
2022-07-12 10:11:35.997 [2142] main/103/test.lua I> [12, 'test_12@tarantool.org', 'some string in exp field']
2022-07-12 10:11:35.997 [2142] main/103/test.lua I> before print archive space "cemetery"
2022-07-12 10:11:35.997 [2142] main/103/test.lua I> -------------- run ------------
2022-07-12 10:11:35.998 [2142] main/116/guardian of "test" I> expiration: task "test" restarted
2022-07-12 10:11:35.998 [2142] main/103/test.lua I> ------------- wait ------------
2022-07-12 10:11:35.998 [2142] main/103/test.lua I> before time = 10:11:35
2022-07-12 10:11:40.998 [2142] main/103/test.lua I> after time = 10:11:40
2022-07-12 10:11:40.998 [2142] main/103/test.lua I> ------------- print -----------
2022-07-12 10:11:40.998 [2142] main/103/test.lua I> After print space "origin"
2022-07-12 10:11:40.998 [2142] main/103/test.lua I> [6, 'test_6@tarantool.org', 1657620701]
2022-07-12 10:11:40.998 [2142] main/103/test.lua I> [7, 'test_7@tarantool.org', 1657620702]
2022-07-12 10:11:40.998 [2142] main/103/test.lua I> [8, 'test_8@tarantool.org', 1657620703]
2022-07-12 10:11:40.998 [2142] main/103/test.lua I> [9, 'test_9@tarantool.org', 1657620704]
2022-07-12 10:11:40.998 [2142] main/103/test.lua I> [10, 'test_10@tarantool.org', 1657620705]
2022-07-12 10:11:40.998 [2142] main/103/test.lua I> after print archive space "cemetery"
2022-07-12 10:11:40.998 [2142] main/103/test.lua I> ['test_0@tarantool.org', 1657620695.9977]
2022-07-12 10:11:40.998 [2142] main/103/test.lua I> ['test_11@tarantool.org', 1657620695.9978]
2022-07-12 10:11:40.998 [2142] main/103/test.lua I> ['test_12@tarantool.org', 1657620695.9979]
2022-07-12 10:11:40.998 [2142] main/103/test.lua I> ['test_1@tarantool.org', 1657620696.999]
2022-07-12 10:11:40.999 [2142] main/103/test.lua I> ['test_2@tarantool.org', 1657620697.9995]
2022-07-12 10:11:40.999 [2142] main/103/test.lua I> ['test_3@tarantool.org', 1657620699.0008]
2022-07-12 10:11:40.999 [2142] main/103/test.lua I> ['test_4@tarantool.org', 1657620699.0009]
2022-07-12 10:11:40.999 [2142] main/103/test.lua I> ['test_5@tarantool.org', 1657620700.0018]
```
You can also reproduce the problem on localhost with a command, but it can take a long time:
```bash
while make test; do :; done
```

### CODE REVIEW

**Review by GRISHNOV — APPROVED** [review]
Hi! LGTM

File: test.lua [hunk 1]
```diff
@@ -298,7 +300,7 @@ test:test('simple expires test',  function(test)
     -- put test tuples
     log.info("-------------- put ------------")
     log.info("put to space " .. prefix_space_id(space_id))
-    put_test_tuples(space_id, 10)
+    put_test_tuples(space_id, 10, 120)
```
Comment (DifferentialOrange) [inline test.lua:303]: So we expect 5 tuples to expire? I think it's worth adding a comment here about this. It's not obvious what should happen after one calls `put_test_tuples(space_id, 10, 120)` until one scroll a couple hundred lines above.

Comment (DifferentialOrange) [reply test.lua:303]: And I don't quite get why below we assert `return cnt == 7`

**Review by DifferentialOrange — APPROVED** [review]
Seems LGTM, but the original tests are not really easy to understand so I have left a couple of questions

File: test.lua (hunk 1 above)
Comment (oleg-jukovec) [reply test.lua:303]: > And I don't quite get why below we assert `return cnt == 7`

Because `put_test_tuples` adds 2 tuples that always expire (field_no == 3 != number):
```
157     -- tuple w/o expiration date                                                
158     local uid = total + 1                                                       
159     add_entry(space_id, uid, get_email(uid), "")                                
160                                                                                 
161     -- tuple w/ invalid expiration date                                         
162     uid = total + 2                                                             
163     add_entry(space_id, uid, get_email(uid), "some string in exp field")
```

Comment (DifferentialOrange) [reply test.lua:308]: Ok, this should be enough
