### PR TITLE
Fix freezes when stopping a task

### LINKED ISSUE #69: Task stop(restart) may freeze up to task.full_scan_delay seconds
We've encountered expd freezing on 
https://github.com/tarantool/expirationd/blob/930c1c4852cb6eea6ac32bb758753ad6d9bd71f3/expirationd.lua#L170

This happens due to worker_fiber being sleepy (so cancel fails), and fiber calling task.start got stuck.
This happened on production, led to malfunctioning cluster, pretty nasty.
Quickfix would be to add fiber.testcancel() after pcall:
https://github.com/tarantool/expirationd/blob/930c1c4852cb6eea6ac32bb758753ad6d9bd71f3/expirationd.lua#L152

I can provide more details regarding reproduceer/test-case, if necessary.

### PR DESCRIPTION
**Pull request by ArtDu**
The problem is that the call to task:stop hangs, because task:stop
sends cancel to the active fibers and waits for these fibers to become
"dead". But there may be some code that can get cancelation using pcall
and skip it, so we have to check the fiber for cancellation.
We do this by checking a flag `worker_canceled` that was previously
only used for atomic iterations. We also fixed the places where this
flag is checked and added comments why in this or that place we
check the cancellation of the worker.

Closes #69

### CODE REVIEW

File: expirationd.lua [hunk 1]
```diff
@@ -166,6 +166,8 @@ local function worker_loop(task)
             end
         end
 
+        --check if fiber was canceled in pcall
+        fiber.testcancel()
```
Comment (olegrok) [inline expirationd.lua:170]: Please add a space between `--` and message. Also please start a comment with a capital letter.

File: test/unit/stop_test.lua [hunk 2]
```diff
@@ -0,0 +1,34 @@
...
+    helpers.init_spaces(g)
+end)
+
+g.after_each(function()
+    helpers.truncate_spaces(g)
+end)
+
+function g.test_cancel_on_pcall()
+    local function on_full_scan_complete()
+        pcall(function() fiber.sleep(1) end)
```
Comment (olegrok) [inline test/unit/stop_test.lua:18]: nit: Could be rewritten as pcall(fiber.sleep, 1)

**Review by olegrok — COMMENTED** [review]
Thanks for your patch, please add more info to commit message and remove `:` after `Closes`.

Also consider my comments below.

File: test/unit/stop_test.lua [hunk 3]
```diff
@@ -0,0 +1,34 @@
...
+
+    local task = expirationd.start("clean_all", g.tree.id, helpers.is_expired_true, {
+        full_scan_delay = 123123123,
+        on_full_scan_complete = on_full_scan_complete
+    })
+    helpers.retrying({}, function()
+        t.assert(task.worker_fiber)
+    end)
+    -- we need to execute in a separate fiber,
+    -- since pcall does not check testcancel and stop may freeze up
```
Comment (ligurio) [inline test/unit/stop_test.lua:29]: Sentence starts with uppercase and dot at the end.
https://www.tarantool.io/en/doc/latest/dev_guide/lua_style_guide/

**Review by ligurio — CHANGES_REQUESTED** [review]
Thanks for the patch! Please add description or explanation of changes to a commit message.

File: expirationd.lua (hunk 1 above)
[the remark this answers is not in the document]
Comment (ArtDu) [reply expirationd.lua:181]: Yes, you are right, I reviewed how these checks are arranged and redid it a bit. I also left comments on each check, about why it should be here. Please look and let's discuss what you think is the best thing to do?

Comment (ArtDu) [reply expirationd.lua:181]: Sorry, I missed the space again ((

File: test/unit/stop_test.lua (hunk 2 above)
Comment (ArtDu) [reply test/unit/stop_test.lua]: Yes, that would be more correct. Fixed

File: test/unit/stop_test.lua [hunk 4]
```diff
@@ -0,0 +1,34 @@
...
+    helpers.truncate_spaces(g)
+end)
+
+function g.test_cancel_on_pcall()
+    local function on_full_scan_complete()
+        pcall(function() fiber.sleep(1) end)
+    end
+
+    local task = expirationd.start("clean_all", g.tree.id, helpers.is_expired_true, {
+        full_scan_delay = 123123123,
```
[the remark this answers is not in the document]
Comment (ArtDu) [reply test/unit/stop_test.lua]: Was rewrite to `local one_hour = 3600`

File: expirationd.lua [hunk 5]
```diff
@@ -166,6 +166,8 @@ local function worker_loop(task)
             end
         end
 
+        --check if fiber was canceled in pcall
```
[the remark this answers is not in the document]
Comment (ArtDu) [reply expirationd.lua]: Yeah, fixed

File: test/unit/stop_test.lua (hunk 3 above)
Comment (ArtDu) [reply test/unit/stop_test.lua]: Sorry, but I could not find in the guideline which you attached the words uppercase and dot, perhaps we need to leave a ticket to the documentation. And we will probably need to create a ticket in `expd` to redo the old comments so that they also match the comments style-guide

File: expirationd.lua [hunk 6]
```diff
@@ -102,6 +102,11 @@ local function default_do_worker_iteration(task)
     local checked_tuples_count = 0
     local vinyl_checked_tuples_count = 0
     if task.atomic_iteration then
+        -- Before starting the transaction,
+        -- since the batch transaction can be long.
```
Comment (olegrok) [inline expirationd.lua:106]: Sorry, but I don't understand that "batch transaction" means.

File: expirationd.lua (hunk 1 above)
[the remark this answers is not in the document]
Comment (olegrok) [reply expirationd.lua:181]: To be honest it looks a bit tricky. Ideally each line should be covered by test. But I guess it's not so.
Anyway "Check if fiber was canceled" doesn't explain why above we use "task.worker_canceled" but here we use testcancel?

File: expirationd.lua [hunk 7]
```diff
@@ -144,12 +155,12 @@ local function worker_loop(task)
...
     while true do
-        if task.worker_canceled then
-            fiber.self():cancel()
-        end
         if (box.cfg.replication_source == nil and box.cfg.replication == nil) or task.force then
             task.on_full_scan_start(task)
             local state, err = pcall(task.do_worker_iteration, task)
+            -- Following functions are on_full_scan*,
+            -- but we probably did not complete the full scan,
+            -- so we should logically check cancellation here.
```
Comment (olegrok) [inline expirationd.lua:163]: It's a bit strange phrase.

Could we perform "non-logical" check? Also I guess it should be "check for cancellation".

**Review by olegrok — COMMENTED** [review]
Thanks for your fixes. See my comments below.

File: expirationd.lua (hunk 6 above)
Comment (ArtDu) [reply expirationd.lua:106]: Can I replace it with transaction per batch?

Comment (olegrok) [reply expirationd.lua:106]: why not just "transaction"?

Comment (ArtDu) [reply expirationd.lua:106]: Yeah, we can write just a transaction)

File: test/unit/stop_test.lua (hunk 3 above)
Comment (ligurio) [reply test/unit/stop_test.lua]: https://github.com/tarantool/doc/issues/2331

File: expirationd.lua (hunk 1 above)
[the remark this answers is not in the document]
Comment (ArtDu) [reply expirationd.lua:181]: We use both test_cancel and task.worker_canceled here.
Check this out, is this a good description?
```diff
@@ -177,11 +177,15 @@ local function worker_loop(task)
             end
         end

-        -- Check if fiber was canceled.
-        fiber.testcancel()
-        -- Then there is sleep and it can be long.
+        -- Check cancellation of fiber,
+        -- then there is sleep and it can be long.
         if task.worker_canceled then
+            -- The worker_canceled flag is used only if we have atomic_iteration = true.
             fiber.self():cancel()
+        else
+            -- Check if fiber was canceled, because pcall
+            -- can catch a cancellation and can skip it.
+            fiber.testcancel()
         end
         -- Full scan iteration is complete, yield
         fiber.sleep(task.full_scan_delay)
```

[the remark this answers is not in the document]
Comment (olegrok) [reply expirationd.lua:181]: > -- Check if fiber was canceled, because pcall
            -- can catch a cancellation and can skip it.
            fiber.testcancel()

Who cancelled this fiber? And why it doesn't switch worker_canceled flag to true?

[the remark this answers is not in the document]
Comment (ArtDu) [reply expirationd.lua:181]: > Who canceled this fiber? And why it doesn't switch worker_canceled flag to true?  
 
We can write about the task:stop logic, but why describe what you can see in the code?
I missed your point, what do you want to see here as comments?

[the remark this answers is not in the document]
Comment (olegrok) [reply expirationd.lua:181]: Seems I told about this part:
https://github.com/tarantool/expirationd/blob/930c1c4852cb6eea6ac32bb758753ad6d9bd71f3/expirationd.lua#L215-L219

It's a bit inconsistent. I thought that stop() turn worker_canceled flag on anyway. But seems it's relevant only for atomic_iteration.

I don't know will anyone support me, but I vote for setup `worker_canceled = true` for not batch_iteration case as well. Seems it also should solve an issue.

[the remark this answers is not in the document]
Comment (ArtDu) [reply expirationd.lua:181]: Yes, this is a good option, then we don't need testcancel check at all. Perhaps it is worth doing so. @ligurio can help discuss it as a third person

File: expirationd.lua (hunk 7 above)
Comment (ArtDu) [reply expirationd.lua]: Did this:
```diff
             local state, err = pcall(task.do_worker_iteration, task)
             -- Following functions are on_full_scan*,
             -- but we probably did not complete the full scan,
-            -- so we should logically check cancellation here.
+            -- so we should check for cancellation here.
             if task.worker_canceled then
                 fiber.self():cancel()
             end
```

File: expirationd.lua (hunk 6 above)
Comment (ArtDu) [reply expirationd.lua]: Did this:
```diff
@@ -103,7 +103,7 @@ local function default_do_worker_iteration(task)
     local vinyl_checked_tuples_count = 0
     if task.atomic_iteration then
         -- Before starting the transaction,
-        -- since the batch transaction can be long.
+        -- since the transaction can be long.
         if task.worker_canceled then
             return true
         end
```

File: expirationd.lua (hunk 1 above)
[the remark this answers is not in the document]
Comment (ligurio) [reply expirationd.lua:181]: Personally I like a variant with `worker_canceled = true` for non-`batch_iteration` as well.

[the remark this answers is not in the document]
Comment (ArtDu) [reply expirationd.lua]: Finished with this. Changed worker_canceled not only for atomic and removed testcancel.

File: test/unit/stop_test.lua [hunk 8]
```diff
@@ -0,0 +1,34 @@
...
+    })
+    helpers.retrying({}, function()
+        t.assert(task.worker_fiber)
+    end)
+    -- We need to execute in a separate fiber,
+    -- since pcall does not check testcancel and stop may freeze up.
+    local f = fiber.create(task.stop, task)
+    helpers.retrying({}, function()
+        t.assert_equals(f:status(), "dead")
+    end)
```
Comment (ligurio) [inline test/unit/stop_test.lua:33]: The fixed bug is about freeze on stop, right now in test you just check that fiber some day finished it's work. But we need to check that fiber will finish during  some time. I would suggest to set explicit timeout to `helpers.retrying()`.

File: expirationd.lua [hunk 9]
```diff
@@ -127,6 +133,11 @@ local function default_do_worker_iteration(task)
                 suspend(task)
             end
             if task.atomic_iteration then
+                -- Before starting the transaction,
+                -- since the batch transaction can be long.
```
Comment (olegrok) [inline expirationd.lua:137]: Seems "batch" is redundant here

File: expirationd.lua [hunk 10]
```diff
@@ -102,6 +102,11 @@ local function default_do_worker_iteration(task)
     local checked_tuples_count = 0
     local vinyl_checked_tuples_count = 0
     if task.atomic_iteration then
+        -- Before starting the transaction,
```
Comment (olegrok) [inline expirationd.lua:105]: "Check before starting transaction, ..." or something similar a phase "Before starting the transaction, since the transaction can be long" without any verb doesn't make sense.

Comment (ArtDu) [reply expirationd.lua]: You are right, fixed on "Check before starting transaction, ..."

File: expirationd.lua (hunk 9 above)
Comment (ArtDu) [reply expirationd.lua]: Yes, deleted that word

File: expirationd.lua [hunk 11]
```diff
@@ -166,6 +177,10 @@ local function worker_loop(task)
             end
         end
 
+        -- There is sleep and it can be long.
```
Comment (olegrok) [inline expirationd.lua:180]: Yes, it can be long. Please add more context to this comment. Currently it's a bit useless.

**Review by ligurio — CHANGES_REQUESTED** [review]

File: test/unit/stop_test.lua (hunk 8 above)
Comment (ArtDu) [reply test/unit/stop_test.lua:33]: There is a default timeout in the helpers.retrying(), 5 seconds. Or do you want it to be visible right in the code?

File: expirationd.lua [hunk 12]
```diff
@@ -127,6 +133,11 @@ local function default_do_worker_iteration(task)
                 suspend(task)
             end
             if task.atomic_iteration then
+                -- Before starting the transaction,
```
[the remark this answers is not in the document]
Comment (ArtDu) [reply expirationd.lua]: Sorry, my fault

File: expirationd.lua (hunk 11 above)
Comment (ArtDu) [reply expirationd.lua]: That's ok? 
```lua
-- If we do not check the fiber for cancellation,
-- then the fiber may fall asleep for a long time, depending on `full_scan_delay`.
-- And a fiber that wants to stop this task can also freeze, a kind of deadlock.
```

File: test/unit/stop_test.lua (hunk 8 above)
Comment (ligurio) [reply test/unit/stop_test.lua:33]: Yep, let's make it at least explicit.

**Review by olegrok — APPROVED** [review]

File: test/unit/stop_test.lua (hunk 8 above)
Comment (ArtDu) [reply test/unit/stop_test.lua]: Made explicit, 5 seconds

File: test/unit/stop_test.lua [hunk 13]
```diff
@@ -0,0 +1,34 @@
+local expirationd = require("expirationd")
```
Comment (ligurio) [inline test/unit/stop_test.lua:1]: Could you please rename file with test to something like `task_test.lua` or `task_stop_test.lua`. Right now it is unclear what kind of stop we test here without looking to a file content. We plan to move TAP tests to luatest format and it would be good to give a clear names for files.

**Review by ligurio — CHANGES_REQUESTED** [review]

File: test/unit/stop_test.lua (hunk 13 above)
Comment (ArtDu) [reply test/unit/stop_test.lua]: Renamed to `task_stop_test.lua`

**Review by ligurio — APPROVED** [review]

**Comment by ligurio** [comment]
LGTM
